### ISSUE TITLE
Global variable RE_NONTERMINAL is not defined

### ISSUE THREAD

**Issue by satbekmyrza** [vrthra/Ewoks#3]
https://github.com/vrthra/Ewoks/blob/0e88a3c9760ee50bf02b8aba3b1b7df25d134c83/src/Parser.py#L167

**Comment by vrthra** [comment]
Thanks for the bug report. `RE_NONTERMINAL = re.compile(r'(<[^<> ]*>)')` is the fix. I will update the code when I have some time.
